name: Android CI

on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: Install dependencies
        run: |
          npm i
    
      - name: Build Android App
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: android/app/build/outputs/apk/release/app-release.apk
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Update this to the AWS region where your S3 bucket is located

      - name: Upload release APK to S3
        run: |
          aws s3 cp android/app/build/outputs/apk/release/app-release.apk s3://reactcicd2705/app-release.apk



